//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoASPDotNetFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHoc
    {
        public string IDMH { get; set; }
        public string Ma_HK { get; set; }
        public string TenMH { get; set; }
        public int SoTC { get; set; }
        public Nullable<int> LyThuyet { get; set; }
        public Nullable<int> ThucHanh { get; set; }
    }
}
