//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoASPDotNetFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NamHoc
    {
        public string Ma_NH { get; set; }
        public string Ten_NH { get; set; }
    }
}
